<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>edu.psu.se411</groupId>
  <artifactId>lab04</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>lab04</name>
  <description>SE411 Lab 04 Maven Project</description>
<url>https://github.com/shajan-mo/SE411_mylabs/tree/main/lab04</url>
<licenses>
    <license>
        <name>Apache License 2.0</name>
        <url>https://www.apache.org/licenses/LICENSE-2.0</url>
    </license>
</licenses>
<organization>
    <name>SE411-PSU</name>
    <url>https://github.com/shajan-mo/SE411_mylabs/tree/main/lab04</url>
</organization>
<developers>
    <developer>
        <name>Shajan</name>
        <email>221410469@psu.edu.sa</email>
    </developer>
</developers>
  <dependencies>
    <dependency>
        <groupId>org.openjfx</groupId>
        <artifactId>javafx-controls</artifactId>
        <version>23</version>
    </dependency>
</dependencies>
<build>
    <plugins>
        <plugin>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-maven-plugin</artifactId>
            <version>0.0.8</version>
            <configuration>
                <mainClass>edu.psu.se411.lab04.Main</mainClass>
            </configuration>
        </plugin>
        <plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-site-plugin</artifactId>
    <version>3.21.0</version>
</plugin>

<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-project-info-reports-plugin</artifactId>
    <version>3.5.0</version>
</plugin>
    </plugins>
    
</build>
</project>